## Numpy的ndarray:一种多维数组的对象 

In [18]:
import numpy as np
from numpy import ndarray
Array=ndarray([(1,2,3),(2,3,4)])
Array

TypeError: an integer is required

In [20]:
data1=[1,2,3.1,4]


In [21]:
arr1=np.array(data1)

In [22]:
arr1

array([ 1. ,  2. ,  3.1,  4. ])

In [23]:
data2=[[1,2,3,4],[2,3,4,5]]

In [24]:
arr2=np.array(data2)

In [25]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [26]:
arr2.shape

(2, 4)

In [27]:
arr2.dtype

dtype('int32')

In [28]:
arr1.dtype

dtype('float64')

In [29]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [33]:
np.zeros((2,3))#np.zeros()args参数为一个integra

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [36]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [46]:
arr3=np.array([1,2,3],dtype=int)
arr3.dtype

dtype('int32')

## ndarray的astype显示的更改dtype 

In [50]:
float_arr=arr3.astype(np.float)
float_arr.dtype

dtype('float64')

In [38]:
arr4=np.asarray(arr3)
arr4

array([1, 2, 3])

In [39]:
id(arr3)

113956544

In [40]:
id(arr4)

113956544

In [52]:
np.dtype?

In [57]:
numeric_string=np.array(['1.0','2','3.0'],dtype=np.string_)
numeric_string.astype(float)


array([ 1.,  2.,  3.])

## 数组和标量间的计算 

In [58]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [60]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [2]:
import numpy as np
from numpy import ndarray
arr=np.array([[1,2,3],[4,5,6]])
1//arr

array([[1, 0, 0],
       [0, 0, 0]], dtype=int32)

## 基本的索引和切片

In [63]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [64]:
arr[:4]

array([0, 1, 2, 3])

In [66]:
arr[4:6]=7#任何修改都在原函数上进行修改，没有进行复制
arr

array([0, 1, 2, 3, 7, 7])

In [67]:
arr_slice=arr[2:4]
arr_slice[1]=8
arr

array([0, 1, 2, 8, 7, 7])

In [68]:
cpy_arr=arr[2:4].copy()
cpy_arr

array([2, 8])

## 二维数组的情况 

In [70]:
arr2d=np.array([[1,2,3],[4,5,6],[5,6,7]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [71]:
arr2d[1]

array([4, 5, 6])

In [72]:
arr2d[0][2]

3

In [73]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,4,5]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 4, 5]]])

In [75]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr3d[0][1][1]#返回的结果都是视图

5

### 切片索引

In [78]:
arr

array([0, 1, 2, 8, 7, 7])

In [79]:
arr[3:6]=3,4,5#分别赋值
arr

array([0, 1, 2, 3, 4, 5])

In [80]:
arr2d


array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [81]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr2d[:2,:1]#二维的切片，在原有的基础上进行

array([[1],
       [4]])

In [88]:
arr2d[:2,:1][1:2]

array([[4]])

In [89]:
arr2d[1,:1]

array([4])

In [90]:
arr2d[1,:3][:2]

array([4, 5])

In [91]:
arr2d[:,:1]

array([[1],
       [4],
       [5]])

### [:,:]','左边是行的轴向，右边是列的轴向，一个：就是一个轴向

In [92]:
arr2d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [93]:
arr2d[1:3]

array([[4, 5, 6],
       [5, 6, 7]])

In [94]:
arr2d[1:3,0:2]

array([[4, 5],
       [5, 6]])

### 布尔型索引

In [97]:
import numpy.random
names=np.array(['bob','joe','will','bob','will','joe','joe'])

data=numpy.random.randn(7,4)

In [98]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], 
      dtype='<U4')

In [99]:
data

array([[-0.48962195,  1.93167464, -0.85368033,  0.37363496],
       [ 0.01227416,  0.80535221, -0.43760622,  0.47839633],
       [-0.84024688, -1.69997256, -0.0056566 , -1.13492443],
       [-0.07649499, -1.73226396,  0.54251189, -0.21748022],
       [ 1.36161788, -0.1653648 ,  1.46412613,  0.58963946],
       [ 0.18242921, -0.35995565, -1.3043292 , -0.76748051],
       [-0.87244788, -0.21482541, -0.61073993,  0.76322682]])

In [100]:
names=='bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

### 布尔型用于数组索引

In [101]:
data[names=='bob']#结果返回true对应的行

array([[-0.48962195,  1.93167464, -0.85368033,  0.37363496],
       [-0.07649499, -1.73226396,  0.54251189, -0.21748022]])

In [103]:
data[names=='bob',:3]#混合使用

array([[-0.48962195,  1.93167464, -0.85368033],
       [-0.07649499, -1.73226396,  0.54251189]])

In [104]:
names!='bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [105]:
data[-(names=='bob')]#对条件进行否定

D:\Anaconda2\envs\python34\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[ 0.01227416,  0.80535221, -0.43760622,  0.47839633],
       [-0.84024688, -1.69997256, -0.0056566 , -1.13492443],
       [ 1.36161788, -0.1653648 ,  1.46412613,  0.58963946],
       [ 0.18242921, -0.35995565, -1.3043292 , -0.76748051],
       [-0.87244788, -0.21482541, -0.61073993,  0.76322682]])

#### 数组中的值用data表示

In [106]:
data[data<0]=0

In [107]:
data

array([[ 0.        ,  1.93167464,  0.        ,  0.37363496],
       [ 0.01227416,  0.80535221,  0.        ,  0.47839633],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.54251189,  0.        ],
       [ 1.36161788,  0.        ,  1.46412613,  0.58963946],
       [ 0.18242921,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.76322682]])

In [108]:
arr=np.empty((8,4))

In [109]:
for i in range (8):
    arr[i]=i

In [110]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

### 花式索引：以特定顺序选取子集，参数为一个整数列表或ndarray

In [111]:
arr[[5,4,3]]#5,4,3为行号

array([[ 5.,  5.,  5.,  5.],
       [ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.]])

In [112]:
arr[[-1,-2,-3]]

array([[ 7.,  7.,  7.,  7.],
       [ 6.,  6.,  6.,  6.],
       [ 5.,  5.,  5.,  5.]])

In [114]:
arr=np.arange(32).reshape(8,4)

In [115]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [117]:
arr[[1,3,5,7]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [122]:
arr[[1,3,5,7],[0,1,2,3]]#0,1,2,3分别是1,3,5,7行的列数最终的元素为（1,0）（3,1）（5,2）（7,3）

array([ 4, 13, 22, 31])

In [123]:
arr[[1,3,5,7]][:,[0,1,2,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [124]:
arr[np.ix_([1,3,5,7],[0,1,2,3])]#np.ix_()就是把一个以为整数数组转换为一个用于选取方形区域的索引器

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

### 花式索引和切片不一样，它总是将数据复制到新的数组中

### 数组转置和轴对换

In [126]:
arr=np.arange(15).reshape((3,5))

In [127]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [129]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [130]:
arr=np.random.randn(6,3)


In [132]:
arr

array([[ 0.56124558, -1.00976322, -0.64571825],
       [-0.62022392, -1.23021644, -0.81872201],
       [-1.77154017,  0.91716795,  0.47558146],
       [-0.3735752 ,  0.29132987,  1.58105564],
       [-1.64487453,  1.84478014,  0.02802882],
       [-0.42835022,  1.57959113, -1.94765371]])

In [131]:
np.dot(arr.T,arr)

array([[ 6.86668345, -5.24839903, -0.49959637],
       [-5.24839903,  9.35744629, -0.46876488],
       [-0.49959637, -0.46876488,  7.60731303]])

### 高维数组的转置，需要得到一个由轴编号组成的元祖才能进行转置

In [133]:
arr=np.arange(16).reshape((2,2,4))

In [134]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [139]:
arr1=arr.transpose((1,0,2))

In [140]:
arr1

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [141]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [142]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [143]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### 通用函数：快速度元素级数组函数

In [146]:
arr=np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [147]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [148]:
np.exp?

In [150]:
x=np.random.randn(8)

In [151]:
y=np.random.randn(8)

In [152]:
x

array([ 0.26529085,  0.14499297, -0.58244481, -0.47167017, -1.50846128,
       -0.96333727,  0.25465563,  1.02478214])

In [153]:
np.maximum(x,y)

array([ 0.26529085,  0.14499297,  0.41773757,  0.89871298,  0.26832809,
       -0.58267724,  0.25465563,  1.02478214])

In [154]:
y

array([ 0.00584114, -0.10083672,  0.41773757,  0.89871298,  0.26832809,
       -0.58267724, -0.41487675,  0.28332986])

### 利用数组进行数据处理

In [155]:
points=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(points,points)

In [156]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [158]:
import matplotlib.pyplot as plt

In [159]:
z=np.sqrt(xs**2+ys**2)

In [160]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [171]:
plt.imshow(z,cmap=plt.cm.gray)
plt.colorbar()

In [2]:
%matplotlib inline
import matplotlib as plt
plt.title('Image plot of $\squrt{x^2+y^2}$ for a grid of values')


AttributeError: 'module' object has no attribute 'title'

### 将条件逻辑表述为数组运算

In [181]:
xarray=np.array([1.1,1.2,1.3,1.4,1.5])
yarray=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])

In [184]:
result=np.where(cond,xarray,yarray)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [185]:
arr=np.random.randn(4,4)
arr

array([[ 0.51616919,  0.52817015,  1.10414221, -0.30752322],
       [-1.50930357, -0.62612222,  0.78152413,  1.42531224],
       [ 0.22285408,  0.84601355,  0.80829115,  0.36873301],
       [ 0.27362138,  0.29138136, -0.38543814, -1.45715378]])

In [186]:
np.where(arr>0,2,-2)

array([[ 2,  2,  2, -2],
       [-2, -2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2, -2, -2]])

In [188]:
arr[data<0]=2
arr

D:\Anaconda2\envs\python34\lib\site-packages\ipykernel\__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 7
  if __name__ == '__main__':


array([[ 0.51616919,  0.52817015,  1.10414221, -0.30752322],
       [-1.50930357, -0.62612222,  0.78152413,  1.42531224],
       [ 0.22285408,  0.84601355,  0.80829115,  0.36873301],
       [ 0.27362138,  0.29138136, -0.38543814, -1.45715378]])

#### 生成原图的视图，不复制

In [193]:
data=np.random.randn(4,4)

In [199]:
data[data<0]=0


In [200]:
data

array([[ 0.        ,  0.31289706,  0.        ,  1.48412481],
       [ 1.82163065,  0.05063423,  0.        ,  0.75116579],
       [ 0.42671433,  1.36909476,  0.86921136,  0.        ],
       [ 0.26548598,  0.        ,  0.        ,  0.57411073]])

In [201]:
data[data>0]=2

In [202]:
data

array([[ 0.,  2.,  0.,  2.],
       [ 2.,  2.,  0.,  2.],
       [ 2.,  2.,  2.,  0.],
       [ 2.,  0.,  0.,  2.]])

### 数学和统计方法

In [203]:
arr=np.random.randn(5,4)


In [204]:
arr.mean()

-0.51282758353218827

In [205]:
np.mean(arr)

-0.51282758353218827

In [206]:
arr.sum()

-10.256551670643764

In [207]:
np.sum(arr)

-10.256551670643764

In [208]:
arr.mean(axis=1)#纵轴

array([-0.22659444, -1.10300104, -0.88458167, -0.53116287,  0.1812021 ])

In [209]:
arr

array([[-0.14100488, -0.46988709, -0.00162128, -0.29386453],
       [-1.23774822, -1.18594684, -0.71697324, -1.27133584],
       [-0.0835133 , -1.40370311, -1.58103202, -0.47007825],
       [-0.5361339 , -0.79043462, -1.24948986,  0.4514069 ],
       [-0.07200443,  1.48606291, -0.20805714, -0.48119294]])

In [210]:
arr.sum(axis=0)#横轴

array([-2.07040474, -2.36390874, -3.75717354, -2.06506466])

In [212]:
arr.sum(axis=1)#纵轴

array([-0.90637777, -4.41200415, -3.53832667, -2.12465148,  0.7248084 ])

In [214]:
arr.sum(1)#axis可省略

array([-0.90637777, -4.41200415, -3.53832667, -2.12465148,  0.7248084 ])

In [215]:
arr=np.random.randn(100)

In [216]:
(arr>0).sum()

63

In [217]:
arr

array([ 0.75621583, -1.45435685,  0.74063553, -0.71852882,  2.28838032,
        2.38713532,  1.0928339 ,  2.49109662, -1.24624033,  0.32685674,
        0.26888896,  0.21894779,  0.1497533 ,  0.02771432, -0.29263246,
        0.03636483,  0.47228474, -0.08022395,  0.64273878, -2.35356588,
        1.05533318, -0.10641411,  0.15669181,  0.71379418,  0.27269737,
        1.38474381, -0.42220982,  0.25657949,  0.479487  , -0.90507411,
        1.04857031, -0.33911031, -1.53417857,  0.5838556 , -0.42259087,
        1.00453034,  1.18095083,  0.28432302,  1.44922403, -0.26781638,
       -0.40148997,  0.32141075,  1.63037797,  1.19039305, -1.26451928,
       -0.9849912 ,  0.64210146,  1.50717731,  0.21151088,  1.62111437,
       -1.39628177,  0.35582496,  0.60603985,  0.42305419,  1.37850642,
        0.9212647 ,  0.71392752,  0.2578432 ,  1.50039202, -1.3181839 ,
       -1.40661194,  0.38898334,  0.42289155,  0.5229699 ,  0.6933815 ,
       -0.14339879,  1.00466968, -1.22881863,  0.86772124, -1.16

### 排序

In [218]:
arr=np.random.randn(10)

In [219]:
arr.sort()

In [220]:
arr

array([-1.85290019, -1.32351786, -0.52458986, -0.44794641,  0.14415019,
        0.5222708 ,  0.83945936,  0.90044427,  1.20374911,  1.52130974])

In [221]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [222]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [223]:
arr.sort(0)

In [224]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [226]:
arr=np.array([[2,3,4,1],[5,6,7,3]])


In [230]:
arr

array([[2, 3, 4, 1],
       [5, 6, 7, 3]])

In [231]:
arr.sort(0)

In [232]:
arr

array([[2, 3, 4, 1],
       [5, 6, 7, 3]])

In [233]:
arr.sort(1)

In [234]:
arr

array([[1, 2, 3, 4],
       [3, 5, 6, 7]])

In [235]:
arr1=np.random.randn(3,5)

In [236]:
arr1

array([[ 2.23679253, -1.10631877, -0.36538476, -2.37052786, -0.69525236],
       [ 2.33348827, -0.50488517, -0.18262594,  0.28625214,  1.59172706],
       [-0.3125478 ,  1.01373683,  0.38776976,  1.64194701,  1.96909882]])

In [237]:
arr1.sort(0)

In [238]:
arr1

array([[-0.3125478 , -1.10631877, -0.36538476, -2.37052786, -0.69525236],
       [ 2.23679253, -0.50488517, -0.18262594,  0.28625214,  1.59172706],
       [ 2.33348827,  1.01373683,  0.38776976,  1.64194701,  1.96909882]])

### 唯一化以及其他的集合逻辑

In [239]:
numbers=np.array([1,2,3,3,2,4,])

In [240]:
numbers.unique()#不能作为实例方法

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [241]:
np.unique(numbers)

array([1, 2, 3, 4])

In [242]:
sorted(set(numbers))

[1, 2, 3, 4]

In [2]:
import numpy as np
values=np.array([1,3,5,6,8])
np.in1d(values,[3,5,6])

array([False,  True,  True,  True, False], dtype=bool)

In [3]:
arr1=np.array([1,2,3,4,6])

In [6]:
arr2=np.array([2,3,4,7,8])

In [7]:
np.setdiff1d(arr1,arr2)

array([1, 6])

In [9]:
np.setxor1d(arr1,arr2)

array([1, 6, 7, 8])

### 用于数组文件的输入输出

In [13]:
arr=np.arange(10)

np.save('some_arr',arr)

In [15]:
np.load('some_arr.npy')#保存时‘。npy’可省略，打开时不可省略

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 多数组保存在一个压缩文件中

In [16]:
np.savez('array_archive',a=arr,b=arr)

In [18]:
arch=np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
type(arch)

numpy.lib.npyio.NpzFile

In [21]:
!type array_ex.txt

系统找不到指定的文件。


### 线性代数

In [23]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])


In [24]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [25]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [26]:
np.ones(3)

array([ 1.,  1.,  1.])

In [28]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [47]:
from numpy.linalg import inv,qr,det ,trace

ImportError: cannot import name 'trace'

In [34]:
x=np.random.randn(5,5)

In [35]:
x

array([[ 0.17407454, -0.08386336, -0.19832656, -1.00776834, -0.60988817],
       [ 0.23319052,  0.10159593,  0.46002122, -1.57424933,  1.39721665],
       [-0.06786889, -0.00522705,  1.12986696, -0.62618945,  0.3818577 ],
       [ 0.11342491,  0.31265996, -0.91572698,  0.44552308, -0.00895647],
       [ 0.7831355 ,  0.58055185, -1.59941509,  0.27964942,  0.1086461 ]])

In [36]:
mat=x.T.dot(x)

In [37]:
inv(mat)

array([[ 18.64285976, -16.55790355,   2.60335184,   3.79381328,   1.258258  ],
       [-16.55790355,  28.54723468,   1.51177913,  -3.56787956,
         -4.24945439],
       [  2.60335184,   1.51177913,   1.67853921,   0.59620137,
         -0.70901153],
       [  3.79381328,  -3.56787956,   0.59620137,   1.18130116,
          0.54502629],
       [  1.258258  ,  -4.24945439,  -0.70901153,   0.54502629,   1.3813854 ]])

In [40]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   1.11022302e-15,  -2.77555756e-16,
         -6.93889390e-16,  -3.88578059e-16],
       [ -6.66133815e-16,   1.00000000e+00,   1.66533454e-16,
          1.38777878e-16,   1.11022302e-16],
       [  3.99680289e-15,  -8.88178420e-16,   1.00000000e+00,
         -6.66133815e-16,   4.44089210e-16],
       [ -2.66453526e-15,   8.88178420e-16,   2.22044605e-16,
          1.00000000e+00,   4.44089210e-16],
       [ -1.33226763e-15,   0.00000000e+00,  -8.88178420e-16,
          0.00000000e+00,   1.00000000e+00]])

In [41]:
q,r=qr(mat)

In [42]:
r

array([[-1.65599258, -1.31323541,  4.51880735, -0.80318642, -0.016636  ],
       [ 0.        , -0.42994922,  2.76338176, -4.30950216,  1.74371382],
       [ 0.        ,  0.        , -2.19050491,  2.38749076, -2.72306305],
       [ 0.        ,  0.        ,  0.        , -0.32260182,  0.30181734],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.21152926]])

In [45]:
det(mat)


0.10642827756894094

In [51]:
from numpy.linalg import eig
eig(mat)

(array([ 7.6295087 ,  3.61710402,  0.0238289 ,  0.12026695,  1.34570271]),
 array([[ 0.11428389,  0.38785105, -0.5889468 , -0.69710221, -0.06083522],
        [ 0.12886871,  0.26191642,  0.79168535, -0.51514039,  0.15052353],
        [-0.70422949, -0.54918652, -0.00840009, -0.42642012,  0.14335378],
        [ 0.60013832, -0.51217724, -0.12553704, -0.13172964,  0.58685281],
        [-0.33797466,  0.4658755 , -0.10269308,  0.22246812,  0.78018922]]))

In [57]:
np.diag(mat)

array([ 0.71545237,  0.45217882,  4.92423684,  4.16266582,  2.48187744])

In [58]:
np.trace(mat)

12.73641128035797

### 随机数的生成

In [59]:
sample=np.random.normal(size=(4,4))#标准正态分布

In [60]:
sample

array([[-0.38937116, -0.36249094,  0.05818707, -0.71525907],
       [-1.28846787, -1.29610675, -0.05174148,  0.55777071],
       [-1.07211625, -0.52136959, -1.44204081,  1.02983678],
       [-0.35641198, -1.09235855, -0.28201216,  0.13757698]])

### 范例：随机漫步

In [62]:
import random
position=0
walk=[position]
step=1000
for i in range(step):
    step=1 if random.randint(0,1)else -1
    position+=step
    walk.append(position)

In [63]:
nsteps=1000


In [64]:
draws=np.random.randint(0,2,size=nsteps)

In [70]:
steps=np.where(draws>0,1,-1)

In [75]:
walk=steps.cumsum()

In [76]:
type(steps)

numpy.ndarray

In [77]:
walk.min()

-8

In [78]:
walk.max()

53

In [79]:
(np.abs(walk)>=10).argmax()

255

In [81]:
np.random.randint?


In [82]:
nwalks=5000

In [83]:
nteps=1000


In [84]:
draws=np.random.randint(0,2,size=(nwalks,nsteps))

In [85]:
steps=np.where(draws>0,1,-1)

In [86]:
walks=steps.cumsum(1)

In [87]:
walks

array([[  1,   0,   1, ...,  34,  33,  32],
       [ -1,  -2,  -3, ..., -40, -39, -40],
       [ -1,  -2,  -1, ..., -18, -19, -20],
       ..., 
       [  1,   0,   1, ...,   8,   7,   8],
       [  1,   2,   1, ...,  -4,  -3,  -4],
       [ -1,   0,   1, ..., -12, -13, -12]], dtype=int32)

In [88]:
walks.max()

112

In [89]:
walks.min()

-111

In [90]:
hsit30=(np.abs(walks)>=30).any(1)

In [91]:
hsit30

array([ True,  True, False, ..., False, False, False], dtype=bool)

In [92]:
hsit30.sum()

3379

In [93]:
crossing_times=(np.abs(walks[hsit30])>=30).argmax()#利用布尔型数组选出选出需要的行

In [94]:
crossing_times.mean()

365.0